name: k8s_tools
namespace: evantage_ws
version: 1.0.0

readme: README.md

description: Collection of roles for Kubernetes & tooling setup for the SUSE Linux Family, based on https://github.com/somaz94/ansible-k8s-iac-tool

authors:
  - ws info@evantage.nl

license_file: LICENSE

tags:
  - kubernetes
  - tooling
  - helm
  - k9s
  - krew
  - krew_plugins
  - kubectl
  - kubectx

dependencies: {}

repository: https://github.com/Evantage-WS/ansible-collection-k8s-tools
