---
galaxy_info:
  author: evantage
  description: Ansible role to install helm
  license: MIT
  min_ansible_version: "2.9"
  role_name: install_helm
  platforms:
    - name: SLES
      versions:
        - all
    - name: opensuse
      versions:
        - all
  galaxy_tags:
    - helm

dependencies: []
