---
galaxy_info:
  author: evantage
  description: Ansible role to install kubectx
  license: MIT
  min_ansible_version: "2.9"
  role_name: install_kubectx
  platforms:
    - name: SLES
      versions:
        - all
    - name: opensuse
      versions:
        - all
  galaxy_tags:
    - kubectx

dependencies: []


