---
galaxy_info:
  author: evantage
  description: Ansible role to install kubectl
  license: MIT
  min_ansible_version: "2.9"
  role_name: install_kubectl
  platforms:
    - name: SLES
      versions:
        - all
    - name: opensuse
      versions:
        - all
  galaxy_tags:
    - kubectl

dependencies: []


